CREATE TABLE USER(
	USER_ID VARCHAR(30) PRIMARY KEY,
  	USER_NAME VARCHAR(30),
  	MAX_TEMP INT,
  	MAX_HUMID INT,
  	MAX_LIGHT INT
);

INSERT INTO USER VALUES("123", "Christina", 30, 60, 500);

SELECT * FROM USER;